# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            TRX
tagline:          TheRomanXpl0it CTF Team
description:      "CTF team composed of students of Sapienza, University of Rome. Part of mhackeroni."
url:              https://theromanxpl0it.github.io/
baseurl:          https://theromanxpl0it.github.io/
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           TheRomanXpl0it
  url:            https://twitter.com/TheRomanXpl0it

paginate:         6
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/TheRomanXpl0it
